# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Summer Institute in Computational Social Science"
email: your-email@domain.com
url: "" # the base hostname & protocol for your site, e.g. http://example.com
brand: Summer Institute in Computational Social Science

current_year: 2025

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - documentation
  - scripts
  - node_modules

collections:
  videos:
    output: true
    permalink: /overview/:name

video_listing:
  search:
    ref: slug
    keys:
      - title
      - content
      - author
  filters:
    - name: Programming Languages
      key: programming_lang
      # "names" is an optional key; used to rename items for display on the filter list. The value
      # used in the video file will be slugified first, then looked up in this dictionary. If a
      # value is found here, it will be used, otherwise the item in the file will be used as-is.
      names:
        css: CSS
        r: R
        python: Python
        rust: Rust
        javascript: JavaScript
    - name: Location
      key: location
    - name: Authors
      key: author

defaults:
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
