name: Jekyll build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with sparse-checkout
        uses: actions/checkout@v4
        with:
          # prevents inclusion of full git history to help ensure runner doesn't deplete disk space
          fetch-depth: 1
          # Include repo root; exclude large materials dir (COMMENT OUT if we need to build with materials)
          sparse-checkout: |
            /
            !/materials/
          sparse-checkout-cone-mode: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler: '2.3.23'  # matches Gemfile.lock (in oct 2025)
          bundler-cache: false

      - name: Cache bundler gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: jekyll-${{ runner.os }}-ruby-2.7-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            jekyll-${{ runner.os }}-ruby-2.7-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install --jobs 4 --retry 3

      - name: Jekyll build
        run: bundle exec jekyll build --trace
